// Default/blank objects for "create new" admin forms (Post/Project editors).
// Deliberately NOT inside a "use client" file: the /admin/*/new Server
// Component pages call these directly while rendering, and a plain function
// exported from a "use client" module cannot be invoked on the server
// (Next.js treats every export of a client file as a client-only reference).
import type { PostInput } from "./actions";
import type { ProjectInput } from "./actions";

export function emptyPost(): PostInput {
  return {
    slug: "",
    title: "",
    titleEn: "",
    titleAr: "",
    excerpt: "",
    excerptEn: "",
    excerptAr: "",
    cover: "https://picsum.photos/seed/new-post/1600/900",
    content: "## مقدمه\n\nمتن مطلب را اینجا بنویسید…",
    contentEn: "",
    contentAr: "",
    category: "استراتژی برند",
    categoryEn: "",
    categoryAr: "",
    tags: [],
    tagsEn: [],
    tagsAr: [],
    featured: false,
    published: true,
    readingMinutes: 3,
    metaTitle: "",
    metaTitleEn: "",
    metaTitleAr: "",
    metaDescription: "",
    metaDescriptionEn: "",
    metaDescriptionAr: "",
    ogImage: "",
    keywords: [],
    keywordsEn: [],
    keywordsAr: [],
  };
}

export function emptyProject(): ProjectInput {
  return {
    slug: "",
    title: "",
    titleEn: "",
    titleAr: "",
    subtitle: "",
    subtitleEn: "",
    subtitleAr: "",
    category: "فیلم تبلیغاتی",
    categoryEn: "",
    categoryAr: "",
    cover: "",
    poster: "",
    heroVideo: "",
    gallery: [],
    year: new Date().getFullYear(),
    location: "تهران، ایران",
    locationEn: "",
    locationAr: "",
    accent: "#6699ff",
    featured: false,
    published: true,
    tags: [],
    tagsEn: [],
    tagsAr: [],
    goal: "",
    goalEn: "",
    goalAr: "",
    problem: "",
    problemEn: "",
    problemAr: "",
    idea: "",
    ideaEn: "",
    ideaAr: "",
    production: "",
    productionEn: "",
    productionAr: "",
    marketing: "",
    marketingEn: "",
    marketingAr: "",
    result: "",
    resultEn: "",
    resultAr: "",
    metrics: [],
    metricsEn: [],
    metricsAr: [],
    beforeImage: "",
    afterImage: "",
    credits: [],
    creditsEn: [],
    creditsAr: [],
    clientId: "",
    serviceSlugs: [],
    industrySlugs: [],
    seo: {
      metaTitle: "",
      metaTitleEn: "",
      metaTitleAr: "",
      metaDescription: "",
      metaDescriptionEn: "",
      metaDescriptionAr: "",
      ogImage: "",
      keywords: [],
      keywordsEn: [],
      keywordsAr: [],
    },
  };
}
