// Generated by scripts/gen-image-variants.mjs — do not edit by hand.
//
// A component checks membership here before offering a srcset, because a
// derived filename that does not exist is a 404 inside a srcset and
// browsers do not fall back from those.

/** 28 files, each with a 420px "-sm.webp" sibling. */
export const MARQUEE_SMALL_VARIANTS: ReadonlySet<string> = new Set([
  "/services/01-brand-film.webp",
  "/services/02-commercial-reels.webp",
  "/services/03-product-photography.webp",
  "/services/04-industrial-photography.webp",
  "/services/05-advertising-photography.webp",
  "/services/06-motion-graphics.webp",
  "/services/07-creative-direction.webp",
  "/services/08-performance-marketing.webp",
  "/services/09-social-media-advertising.webp",
  "/services/10-audience-research.webp",
  "/services/11-campaign-strategy.webp",
  "/services/12-media-planning.webp",
  "/services/13-analytics-reporting.webp",
  "/services/14-conversion-optimization.webp",
  "/services/15-logo-design.webp",
  "/services/16-visual-identity.webp",
  "/services/17-typography.webp",
  "/services/18-brand-book.webp",
  "/services/19-packaging.webp",
  "/services/20-advertising-design.webp",
  "/services/21-social-media-design.webp",
  "/services/28-web-design.webp",
  "/services/29-ui-design.webp",
  "/services/30-ux-design.webp",
  "/services/32-landing-page.webp",
  "/services/33-ecommerce.webp",
  "/services/34-dashboard-web-apps.webp",
  "/services/35-website-redesign.webp",
]);

/** 28 files, each with a 600px "-sm.webp" sibling. */
export const ARC_SMALL_VARIANTS: ReadonlySet<string> = new Set([
  "/service-cards/advertising-design.webp",
  "/service-cards/advertising-photography.webp",
  "/service-cards/architecture-photography.webp",
  "/service-cards/audience-persona.webp",
  "/service-cards/brand-book.webp",
  "/service-cards/campaign-design.webp",
  "/service-cards/content-seo.webp",
  "/service-cards/content-strategy.webp",
  "/service-cards/copywriting.webp",
  "/service-cards/corporate-portrait.webp",
  "/service-cards/digital-strategy.webp",
  "/service-cards/food-photography.webp",
  "/service-cards/industrial-photography.webp",
  "/service-cards/keyword-research.webp",
  "/service-cards/lifestyle-photography.webp",
  "/service-cards/local-seo.webp",
  "/service-cards/logo-design.webp",
  "/service-cards/packaging-design.webp",
  "/service-cards/performance-marketing.webp",
  "/service-cards/product-photography.webp",
  "/service-cards/social-media-design.webp",
  "/service-cards/social-media-management.webp",
  "/service-cards/technical-seo.webp",
  "/service-cards/typography.webp",
  "/service-cards/ui-design.webp",
  "/service-cards/ux-design.webp",
  "/service-cards/visual-identity.webp",
  "/service-cards/web-development.webp",
]);

/** The smaller sibling of a path known to be in one of the sets above. */
export function smallVariant(path: string): string {
  return path.slice(0, -".webp".length) + "-sm.webp";
}
